---
  - hosts: all
    become: True
    remote_user: devops
    tasks:
      - name: Install httpd package
        yum: name=httpd state=present
        register: result
      - debug: var=result
        failed_when: "result.rc != 2"

