---
  - hosts: all
    become: True
    remote_user: devops
    tasks:
      - name: Not working play
        yum: name=nopkg state=present
        ignore_errors: yes
      - name: Dialog-package
        yum: name=dialog state=present


