---
  - hosts: servera.lab.example.com
    become: True
    remote_user: devops
    vars:
      users:
        - test1
        - test2
    tasks:
      - name: Adding users
        user: name="{{ item }}"
        with_items: "{{ users }}"

